export enum ActionTypes {
    GET_MATCHES_PAGINATED = "GET_MATCHES_PAGINATED",
    GET_MATCH = "GET_MATCH",
    GET_MATCHES = "GET_MATCHES",
    CREATE_MATCH = "CREATE_MATCH",
    UPDATE_MATCH = "UPDATE_MATCH",
    DELETE_MATCH = "DELETE_MATCH",
  }
  