export enum ActionTypes {
  GET_EDITORS_PAGINATED = "GET_EDITORS_PAGINATED",
  GET_EDITOR = "GET_EDITOR",
  GET_EDITORS = "GET_EDITORS",
  CREATE_EDITOR = "CREATE_EDITOR",
  UPDATE_EDITOR = "UPDATE_EDITOR",
  DELETE_EDITOR = "DELETE_EDITOR",
}
