export enum MutationTypes {
  SET_LOADING = "SET_LOADING",
  SET_EDITOR = "SET_EDITOR",
  SET_EDITORS = "SET_EDITORS",
  SET_EDITORS_PAGINATION = "SET_EDITORS_PAGINATION",
  SET_EDITOR_ID = "SET_EDITOR_ID",
}
