export enum ActionTypes {
  GET_MATCHES = "GET_MATCHES",
  GET_MATCH = "GET_MATCH",
  CREATE_MATCH = "CREATE_MATCH",
  UPDATE_MATCH = "UPDATE_MATCH",
  END_MATCH = "END_MATCH",
  GET_CHAT = "GET_CHAT",
  GET_EDITOR = "GET_EDITOR",
  EXECUTE_CODE = "EXECUTE_CODE",
  CREATE_RATING = "CREATE_RATING",
}
