export enum MutationTypes {
  SET_LOADING = "SET_LOADING",
  SET_MATCH = "SET_MATCH",
  SET_MATCHES = "SET_MATCHES",
  SET_MATCHES_PAGINATION = "SET_MATCHES_PAGINATION",
  SET_OPEN_MATCHING_DIALOG = "SET_OPEN_MATCHING_DIALOG",
  SET_OPEN_ELO_MATCH_DIALOG = "SET_OPEN_ELO_MATCH_DIALOG",
  UPDATE_CHAT_MESSAGES = "UPDATE_CHAT_MESSAGES",
  UPDATE_CODES = "UPDATE_CODES",
  SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES",
}
