export enum ActionTypes {
  GET_QUESTIONS_PAGINATED = "GET_QUESTIONS_PAGINATED",
  GET_QUESTION = "GET_QUESTION",
  GET_QUESTION_TOPICS = "GET_QUESTION_TOPICS",
  GET_FEATURED_QUESTION_TOPICS = "GET_FEATURED_QUESTION_TOPICS",
}
