export enum MutationTypes {
  SET_LOADING = "SET_LOADING",
  SET_QUESTION = "SET_QUESTION",
  SET_QUESTIONS = "SET_QUESTIONS",
  SET_QUESTIONS_PAGINATION = "SET_QUESTIONS_PAGINATION",
  SET_QUESTION_TOPICS = "SET_QUESTION_TOPICS",
  SET_SELECTED_TOPICS = "SET_SELECTED_TOPICS",
}
