export enum ActionTypes {
  GET_QUESTIONS_PAGINATED = "GET_QUESTIONS_PAGINATED",
  GET_QUESTION = "GET_QUESTION",
  GET_QUESTION_TOPICS = "GET_QUESTION_TOPICS",
  DELETE_QUESTION = "DELETE_QUESTION",
  CREATE_QUESTION = "CREATE_QUESTION",
  UPDATE_QUESTION = "UPDATE_QUESTION",
}
