export enum ActionTypes {
  GET_USERS_PAGINATED = "GET_USERS_PAGINATED",
  GET_USER = "GET_USER",
  GET_USERS = "GET_USERS",
  CREATE_USER = "CREATE_USER",
  CREATE_ADMIN = "CREATE_ADMIN",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
}
